### ISSUE TITLE
[Epic] Refined collateral interactions

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#46]
- [ ] https://github.com/codex-storage/nim-codex/issues/598
- [ ] https://github.com/codex-storage/nim-codex/issues/602 More info: maxCollateralPerByte – instead of SP setting their maxCollateralPerByte, they would set their max storage size and max collateral. maxCollateralPerByte can then be calculated by storage available/collateral available. After each slot is serviced, the value would be recalculated for the next availability matching. 
- [ ] https://github.com/codex-storage/nim-codex/issues/460
- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/71
- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/70
- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/102
- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/98

**Comment by AuHau** [comment]
@emizzle I have renamed the epic  ("collateral" -> "contract") as while it tackles some of the collateral issues, it also tackles some general contract related issues ;-) Let me know if you think otherwise!
