### ISSUE TITLE
[Epic] Deploy testnet on an Ethereum L2

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#47]
- [ ] deploy testnet on L2 - deployment only (likely Arbitrum)
  - [ ] devops effort to run a L2 and expose an RPC endpoint, have all testnet codex nodes using that endpoint and the marketplace address on the L2
- [ ] https://github.com/codex-storage/nim-codex/issues/804

**Comment by emizzle** [comment]
Moved reorg task to https://github.com/codex-storage/codex-pm/issues/51, and the remaining task is mostly done and out of our court.
