### ISSUE TITLE
[Epic] Contracts formal verification and audit

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#48]
- [ ] Formal verification with Certora (work with Vac team)
  - [ ] https://github.com/codex-storage/codex-contracts-eth/pull/113
  - [ ] https://github.com/codex-storage/codex-contracts-eth/issues/114
- [ ] Audit via external team
