### ISSUE TITLE
[Epic] Contract bugs / small improvements

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#49]
- [x] https://github.com/codex-storage/codex-contracts-eth/issues/103: collection of smaller issues discovered
- [x] https://github.com/codex-storage/codex-contracts-eth/issues/104
- [x] https://github.com/codex-storage/codex-contracts-eth/issues/105
- [x] https://github.com/codex-storage/codex-contracts-eth/issues/106
~~- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/174~~
