### ISSUE TITLE
[Epic] Node bugs / small improvements

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#52]
- [ ] https://github.com/codex-storage/nim-codex/issues/564
- [ ] https://github.com/codex-storage/nim-codex/issues/563
- [ ] https://github.com/codex-storage/nim-codex/issues/394
- [ ] https://github.com/codex-storage/nim-codex/issues/370
