### ISSUE TITLE
[Epic] Data repair

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-pm#54]
- [ ] https://github.com/codex-storage/codex-contracts-eth/issues/100
- [ ] https://github.com/codex-storage/nim-codex/issues/378
- [ ] https://github.com/codex-storage/nim-codex/issues/777
- [ ] Data download needs to do erasure coding reconstruction
