### ISSUE TITLE
[Epic] NAT traversal

### ISSUE THREAD

**Issue by gmega** [codex-storage/codex-pm#87]
- [x] https://github.com/codex-storage/codex-pm/issues/85
- [x] https://github.com/codex-storage/codex-pm/issues/84
- [x] https://github.com/codex-storage/codex-pm/issues/86
